apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::306237160524:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-B3LDHr1A6mq8
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::306237160524:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-15T04:28:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1214"
  uid: 41ce40b8-511e-49d7-a781-b813615a5a92