apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::306237160524:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-XesTbzlgNzsb
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::306237160524:user/sureshuu
      username: sureshuu
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-20T04:44:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1218"
  uid: a9c74bf6-8e3a-4ef6-be5d-84063e300a0f