apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::306237160524:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-42eSOpMF9Jee
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-07-14T03:49:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1152"
  uid: 94c09a82-63bc-4558-a930-c69b98e00526